version: 2.1
jobs:
   build:
      docker: 
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm install -y
        - save_cache:
            key: "npm-packages"
            paths:
              - /src/node_modules
        - run: npm run lint

workflows:
   webapp:
      jobs: 
        - build 


